env:
  APP_REFRESH: true
server:
  command: "php ./vendor/bin/rr-worker start --relay-dsn unix:///tmp/concal-rr-rpc.sock"
  relay: "unix:///tmp/concal-rr-rpc.sock"
http:
  address: "0.0.0.0:9000"
  middleware: [ "static" ]
  http2:
    enabled: true
    h2c: true
    maxConcurrentStreams: 128
  static:
    dir: public
reload:
  interval: 1s
  patterns: [ '.php' ]
  services:
    http:
      dirs: [ '' ]
      recursive: true
