version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - TZ=${TZ}
    tty: true
    volumes:
      - .:/code
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
      - js
  js:
    build:
      context: .
      dockerfile: ./docker/js/Dockerfile
    volumes:
      - .:/code
      - /code/node_modules
      - ./public:/code/public
  web:
    image: nginx:latest
    volumes:
      - ./docker/web/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - 80:80
  db:
    image: mysql:5.7
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    ports:
      - 3306:3306

volumes:
  db-store:
