version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - TZ=${TZ}
    tty: true
    volumes:
      - .:/code:cached
      - /code/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
      - js
    ports:
      - 9000:9000
  js:
    build:
      context: .
      dockerfile: ./docker/js/Dockerfile
    volumes:
      - .:/code:cached
      - /code/node_modules
      - /code/.yarn
      - ./.yarn/releases:/code/.yarn/releases
  web:
    image: nginx:latest
    volumes:
      - ./docker/web/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - 80:80
  db:
    image: mariadb:10.5.7
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    ports:
      - 3306:3306
volumes:
  db-store:
